### ISSUE TITLE
@angular errors

### ISSUE THREAD

**Issue by mvartani76** [mvartani76/MyBackgroundLocationIonicApp#1]
Receiving the following error when running `ionic cordova run android`

An unhandled exception occurred: Error: ENOENT: no such file or directory, lstat 'C:/Users/Mike Vartanian/Documents/ViralTrak/test/fme/tsconfig.app.json'
    at Object.lstatSync (fs.js:841:3)
    at NodeJSFileSystem.lstat (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\node_js_file_system.js:38:72)
    at calcProjectFileAndBasePath (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular\compiler-cli\src\perform_compile.js:114:31)
    at Object.readConfiguration (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular\compiler-cli\src\perform_compile.js:132:22)
    at Object.readTsconfig (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:25:29)
    at generateWebpackConfig (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:100:12)
    at Object.generateBrowserWebpackConfigFromContext (C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:111:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by mvartani76** [comment]
Going to try downrevisioning the angular plugins mentioned.

**Comment by mvartani76** [comment]
Changed package.json to the following..

{
  "name": "ionic4-background-geo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/background-geolocation": "^5.23.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/http": "^5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.1.0",
    "cordova-android": "^8.1.0",
    "cordova-plugin-advanced-http": "^2.4.1",
    "cordova-plugin-file": "^6.0.2",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.12.3",
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/core": "~7.2.3",
    "@angular-devkit/schematics": "~7.2.3",
    "@angular/cli": "~7.3.1",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "^2.1.1",
    "@mauron85/cordova-plugin-background-geolocation": "^3.0.7",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "@mauron85/cordova-plugin-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      },
      "cordova-plugin-advanced-http": {
        "OKHTTP_VERSION": "3.10.0"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      }
    },
    "platforms": [
      "android"
    ]
  }
}


Now receive this error message...

C:\Users\Mike Vartanian\Documents\ViralTrak\test\fme (master) (ionic4-background-geo@0.0.1)
λ ionic cordova run android
[INFO] Hardware device(s) found for android. Using --device.
> ng.cmd run app:ionic-cordova-build --platform=android
Schema validation failed with the following errors:
  Data path ".builders['cordova-build']" should have required property 'class'.
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.
        Re-running this command with the --verbose flag may provide more information.

Going to just sync the package.json file.
