### ISSUE TITLE
Unable to build/run iOS code

### ISSUE THREAD

**Issue by mvartani76** [mvartani76/MyBackgroundLocationIonicApp#5]
With the following configuration, I am unable to emulate/run the the application in iOS.

Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.10
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.1.2, (and 8 other plugins)

Utility:

   cordova-res : 0.12.1
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.9.1 (/usr/local/Cellar/node/12.9.1/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146

Here are the error(s).

(node:7346) UnhandledPromiseRejectionWarning: /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:57
                    if(device.name === deviceType.name || device.name === deviceType.name.replace(/-inch/g, ’ inch’))
                                                                                                            

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/build.js:126:31
    at _fulfilled (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:816:13)
(node:7346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> native-run ios --app platforms/ios/build/emulator/BackgroundLocation.app --virtual
[native-run] ERR_UNKNOWN: Path 'platforms/ios/build/emulator/BackgroundLocation.app' not found
[native-run] 
[native-run] 	More details for this error may be available online:
[native-run] 
[native-run] 	https://github.com/ionic-team/native-run/wiki/Android-Errors
[ERROR] An error occurred while running subprocess native-run.

**Comment by mvartani76** [comment]
Here is the output of **ionic cordova emulate ios --list**
```
> native-run ios --list --virtual
[native-run] 
[native-run] Virtual Devices:
[native-run] 
[native-run]   iPad (7th generation) 13.4 33C3B1B9-3A97-48E5-A9E0-ACC4D789F6C1
[native-run]   iPad Air (3rd generation) 13.4 F54C1AB1-4EF1-4C88-8704-7497068877CC
[native-run]   iPad Pro (11-inch) (2nd generation) 13.4 CFFB342C-ECE7-4364-83E9-EA1B960727EE
[native-run]   iPad Pro (12.9-inch) (4th generation) 13.4 02F85D87-EFD1-48E1-A8CC-FCFAF5D7EB1B
[native-run]   iPad Pro (9.7-inch) 13.4 29C81C14-6CF3-4F62-BD18-0312B6A55B54
[native-run]   iPhone 11 13.4 91CCA27D-8348-4310-9E95-9D64194C8B99
[native-run]   iPhone 11 Pro 13.4 14EC623D-A659-4F17-A815-BAC9C6C630E8
[native-run]   iPhone 11 Pro Max 13.4 4567E205-8555-4E04-B43A-94AA9ECE2C4A
[native-run]   iPhone 8 13.4 B090D3F8-CD09-4490-9286-471FB59412C9
[native-run]   iPhone 8 Plus 13.4 4CE55BE3-516E-4DCE-8186-656793E00504
```

**Comment by mvartani76** [comment]
output of **ionic cordova build ios**

```
Plugin "cordova-plugin-background-geolocation" already installed on ios.
(node:7579) UnhandledPromiseRejectionWarning: /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:57
                    if(device.name === deviceType.name || device.name === deviceType.name.replace(/-inch/g, ’ inch’))
                                                                                                            

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/build.js:126:31
    at _fulfilled (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:816:13)
(node:7579) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7579) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by mvartani76** [comment]
output of **cordova run --list**

```
cordova run --list
Available ios devices:
Available ios virtual devices:
```

**Comment by mvartani76** [comment]
also tried running the following commands:

```
npm install plist
npm install xcode
ionic cordova platform remove ios
ionic cordova platform add ios
```

after running **ionic cordova build ios**, i get the following error

```
Discovered plugin "@mauron85/cordova-plugin-background-geolocation" in config.xml. Adding it to the project
Plugin "cordova-plugin-background-geolocation" already installed on ios.
(node:8414) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:54:45
    at Array.forEach (<anonymous>)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:52:44
    at Array.reduce (<anonymous>)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:50:57
    at Array.reduce (<anonymous>)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/lib/list-emulator-build-targets:45:28
    at _fulfilled (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/cordova/node_modules/q/q.js:816:13)
(node:8414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mvartani76** [comment]
doing the following seemed to help a bit (gets farther long in the build process)

```
ionic cordova platform remove ios
ionic cordova platform add ios@latest
```

now the **ionic cordova bull ios** error is as follows:

```
ld: 422 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/platforms/ios/build/emulator/BackgroundLocation.app/BackgroundLocation normal x86_64
(1 failure)
(node:8873) UnhandledPromiseRejectionWarning: Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/michaelvartanian/Documents/IonicProjects/MyBackgroundLocationIonicApp/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:8873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8873) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by mvartani76** [comment]
output of **cordova plugin list**

```
cordova-plugin-advanced-http 2.0.9 "Advanced HTTP plugin"
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 3.0.3 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Comment by mvartani76** [comment]
It turns out that two of the plugins were using the same symbols..

```
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-mauron85-background-geolocation 3.0.3 "CDVBackgroundGeolocation"
```

removed the latter as that plugin has been deprecated

`cordova plugin remove cordova-plugin-mauron85-background-geolocation`

now the following commands work and I am able to bring up the app in the iOS simulation.

```
ionic cordova build ios
ionic cordova emulate ios
```
